# -*- coding: utf-8 -*-
"""Reddit_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FI1S1kb43ANmax6uladtMYJP-zo-Vu9Q
"""

# Install necessary packages
!pip install praw requests schedule
!pip install groq
from groq import Groq

import os
import requests
import praw
import schedule
import time
import logging

# Set up basic logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')



# Import Groq client after installing it
client = Groq(api_key="GROQ_API_KEY")

# Setup and authenticate with Reddit API
reddit = praw.Reddit(
    client_id='REDDIT_CLIENT_ID',
    client_secret='REDDIT_CLIENT_SECRET',
    password='REDDIT_PASS',
    user_agent='script:reddit_bot:v1.0 (by /u/your_username)',
    username='REDDIT_USER_ID'
)

def generate_and_post():
    try:
        # Generate title and content for the story
        chat_completion = client.chat.completions.create(
            messages=[
                {"role": "user",
                 "content": "Generate a story with a title and content",
                }
            ],
            model="llama-3.3-70b-versatile",
        )

        # Extract the title and content from the response
        response = chat_completion.choices[0].message.content
        parts = response.split('\n', 1)  # Split only at the first newline
        title = parts[0].strip('* ')  # Remove asterisks and spaces around the title
        content = parts[1] if len(parts) > 1 else ""

        # Submit the post to Reddit
        subreddit_name = "test"
        subreddit = reddit.subreddit(subreddit_name)
        post = subreddit.submit(title=title, selftext=content)
        logging.info(f"Posted to Reddit: {title}")
    except Exception as e:
        logging.error(f"Failed to generate or post content due to: {e}")

# Schedule the task to run 5 minutes after script starts
schedule.every().minute.at(":05").do(generate_and_post)

while True:
    schedule.run_pending()
    time.sleep(1)
